### ISSUE TITLE
Improved renaming when URLs are in title

### ISSUE THREAD

**Issue by jtcramer** [delucks/gtd.py#2]
When the attached URL does not correspond to an HTML file (e.g. a PDF), the renamed link is garbled text, which also garbles the prompt. It would be good to detect if the content is HTML, or if the obtained title is "valid" text. A possible alternative in this case would be to remove the link from the title string. This option would be nice in general.

An additional feature that could be useful would be to have the ability to insert the web page title (and perhaps some additional metadata) into the renamed title using some kind of format string type input. (e.g. `Read the article "%{title}"`)

**Comment by delucks** [comment]
I dig the idea of a formatting language for inserting bits of metadata about the page as you suggest. I'm going to implement that after fixing the behavior for content-types that aren't text/html.

**Comment by delucks** [comment]
@jtcramer could you look over #3 ?

**Comment by jtcramer** [comment]
I left some review comments. Mostly looks good but it'd be good to check for links in a more robust way.

**Comment by delucks** [comment]
Fixed in #3
